### ISSUE TITLE
problem viewing poll

### ISSUE THREAD

**Issue by DrumsnChocolate** [csvalpha/amber-ui#55] opened 2019-11-05 11:15 UTC
### How to reproduce
1. go to a poll (in this case specifically https://csvalpha.nl/polls/224)
2. no clue, haven't tried to reproduce it

### Expected behaviour
View the poll options and be able to vote. Not be able to view the voting results before having voted.

### Current behaviour
Instead of viewing the options, I could suddenly see the voting results before I voted, and weird labels. See screenshot.
![image](https://user-images.githubusercontent.com/32799956/68201020-49984e00-ffc1-11e9-9c9c-a0c6f6589c87.png)

**Comment by Matthijsy** [comment] 2019-11-06 21:26
Might be related with this issue, when looking at the moment of the error and the post of this issue. https://sentry.io/organizations/csvalpha/issues/1315592339/?referrer=slack

**Comment by Matthijsy** [comment] 2020-01-03 19:00
In second opinion, that bug is not related. We cannot reproduce, so I close this bug. @DrumsnChocolate If you know how to reproduce this we can re-open this issue

**Closed by Matthijsy** 2020-01-03 19:00 UTC
